// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWjm9mFHSWRTqbxPcDJo88y0eDAij_YlQ',
    appId: '1:331098715879:web:81aca332cf21a917cb9442',
    messagingSenderId: '331098715879',
    projectId: 'scholarhub-85477',
    authDomain: 'scholarhub-85477.firebaseapp.com',
    storageBucket: 'scholarhub-85477.firebasestorage.app',
    measurementId: 'G-5ZPXHBF2GM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUDzS1Alp2Ye5J0BSIZeiASALvVodLL5A',
    appId: '1:331098715879:android:545eee5ded8df5a9cb9442',
    messagingSenderId: '331098715879',
    projectId: 'scholarhub-85477',
    storageBucket: 'scholarhub-85477.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZBzv2jqD-HEDV6_uObXZRPSnoDwjqj1s',
    appId: '1:331098715879:ios:4c753e330ed91ef7cb9442',
    messagingSenderId: '331098715879',
    projectId: 'scholarhub-85477',
    storageBucket: 'scholarhub-85477.firebasestorage.app',
    iosBundleId: 'com.scholarhub.scholarhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZBzv2jqD-HEDV6_uObXZRPSnoDwjqj1s',
    appId: '1:331098715879:ios:4c753e330ed91ef7cb9442',
    messagingSenderId: '331098715879',
    projectId: 'scholarhub-85477',
    storageBucket: 'scholarhub-85477.firebasestorage.app',
    iosBundleId: 'com.scholarhub.scholarhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWjm9mFHSWRTqbxPcDJo88y0eDAij_YlQ',
    appId: '1:331098715879:web:9154525444962d2bcb9442',
    messagingSenderId: '331098715879',
    projectId: 'scholarhub-85477',
    authDomain: 'scholarhub-85477.firebaseapp.com',
    storageBucket: 'scholarhub-85477.firebasestorage.app',
    measurementId: 'G-9LT2TNCYR9',
  );
}
